//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeBooker
    {
        public int Id { get; set; }
        public string Project { get; set; }
        public string Time { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsRemoved { get; set; }
    }
}
